Neos:
  Neos:
    fusion:
      autoInclude:
        'VIVOMEDIA.Fusion.CacheVisualisation': true

VIVOMEDIA:
  Fusion:
    CacheVisualisation:
      enabled: false
      output:
        wrapperClassName: 'vivomedia-cachevisualisation'
        itemClassName:
          cached: 'vivomedia-cachevisualisation-cached'
          uncached: 'vivomedia-cachevisualisation-uncached'
          dynamic: 'vivomedia-cachevisualisation-dynamic'
      pathBlacklist:
        - 'root'
        - 'root<Neos.Fusion:Case>/default'
        - 'root<Neos.Fusion:Case>/default<Neos.Fusion:Matcher>/element<Neos.NodeTypes:Page.Document>'
        - 'root<Neos.Fusion:Case>/default<Neos.Fusion:Matcher>/element<Neos.NodeTypes:Page.Document>/head<Neos.Fusion:Array>/neosBackendEndpoints'
        - 'root<Neos.Fusion:Case>/default<Neos.Fusion:Matcher>/element<Neos.NodeTypes:Page.Document>/head<Neos.Fusion:Array>/neosBackendHeader'
